### PR TITLE
Add support of proxy to Conversation Nodes

### PR DESCRIPTION
**Pull request by kenime**
Added support of proxy to Conversation Nodes. Proxy with basic auth is also supported.

### CODE REVIEW

**Comment by chughts** [comment]
Please provide an explanation for this pull request.

**Comment by kenime** [comment]
The title is self explanatory; added proxy support for conversation node.

**Comment by chughts** [comment]
Unfortunately for you it isn't self explanatory to me.

**Comment by kenime** [comment]
The underlying request module support http proxy but there is no way to configure in the node property page. The only way to do so was to set node.js global variable http_proxy but it will impact other connections as well, which in many case is not ideal (imagine connection to Watson / internet requires proxy but internal doesn’t).
Therefore, I have added proxy configuration to conversation node configuration html and add  the corresponding configuration to ServiceSettings.

**Comment by chughts** [comment]
Has the change been tested, both with and without a proxy?

**Comment by chughts** [comment]
I can ignore the codacy reports, but I need confirmation that you have successfully tested this code change both behind firewall proxy, and without a proxy.

**Comment by chughts** [comment]
I would like to include this fix, so please reconsider resubmitting. I will, however, still need you to confirm that the change has been tested to work both with and without a proxy.

**Pull request closed without merging**
