### PR TITLE
add word count function of Japanese

### PR DESCRIPTION
**Pull request by yuichi-tanaka**
add: for word count function of Japanse

Is the same as below the Pull-request:
https://github.com/node-red/node-red-node-watson/pull/6

### CODE REVIEW

**Comment by chughts** [comment]
We can not accept any pull requests for which the CLA is not signed. The word count function should go into payload utilities. All the aspects highlighted by codacy need to to be resolved.

**Comment by chughts** [comment]
Thanks for signing the license, and moving the code to payload utilities. This will allow us to resume the word count in other nodes should we need to. 

I waiting waiting on codacy.

**Comment by chughts** [comment]
Still some codacy problems. There are also some changes that others have made that you need to merge in. Normally a git pull upstream master should do it.

**Comment by chughts** [comment]
I will be creating a new release this weekend. You will need to rebase against updates from other contributors.

**Comment by yuichi-tanaka** [comment]
I rebase this repository.
I fixed codacy problems.
but i don't understand why i got codacy check to red.
What had i better do?

**Comment by chughts** [comment]
As the tokeniser is built asynchrnously, will it be built in time for the word count function to use it?

**Comment by yuichi-tanaka** [comment]
@chughts Thank you for your advice. :)
I changed it.

**Comment by chughts** [comment]
Have you tested with both Japanese and English text?

Reason for asking is this code:

```
if (ct === 'ja') {
      fn = function(txt, cb) {
        kuromoji.builder({dicPath: dic_dir}).build(function(err, tknz) {
          if (err) {
            throw err;
          }
          tokenizer = tknz;
          return cb(tokenizer.tokenize(txt).length);
        });
      };
```

kuromoji.builder.build  seems to be asynchronous. If it is then while it is waiting the rest of the word count finishes and hits the return for non-japanese text. I think you need if else clauses that ensure that for Japanese text the tokenised return is the only return from word count.

**Comment by yuichi-tanaka** [comment]
kuromoji.builder.build is asynchronous. but tokenizer.tokenize is synchronous.

My test code

```
var pay_utils= require('./utilities/payload-utils');
var wc = pay_utils.word_count('ja');
var wc_en = pay_utils.word_count('en');

var jp_only = '私は猫が好きです';
var jp_en = '私は猫が好きです(I like cats.)';

//jp
wc(jp_only,function(count){
  console.log('type jp, txt jp:', count); //=>type jp, txt jp: 6
});
wc(jp_en,function(count){
  console.log('type jp, txt jp_en:', count); //=>type jp, txt jp_en: 13
});

//en
wc_en(jp_only,function(count){
  console.log('type en, txt jp:', count); //=>type en, txt jp: 1
});
wc_en(jp_en,function(count){
  console.log('type en, txt jp_en:', count); //=>type en, txt jp_en: 3
});
```

**Comment by chughts** [comment]
That is good. Hopefully final question - have you tested the node with English and with Japanese?

**Comment by yuichi-tanaka** [comment]
Yes, I tested them.

flow in Japanese: 

```
[{"id":"c19b28e1.5e5618","type":"debug","z":"a8a4e460.ecf2c","name":"","active":true,"console":"false","complete":"insights","x":785,"y":491.75,"wires":[]},{"id":"135f0d7b.ccc7fb","type":"watson-personality-insights","z":"a8a4e460.ecf2c","name":"Sample Japanese","lang":"ja","x":609,"y":492.5,"wires":[["c19b28e1.5e5618"]]},{"id":"bba8d3ff.4d506","type":"function","z":"a8a4e460.ecf2c","name":"Yahoo! news in Japanese","func":"msg.payload = \"政府は成人年齢を現行の「２０歳」から「１８歳」に引き下げるための民法改正案を来年の通常国会に提出する方針を固めた。複数の政府関係者が１４日、明らかにした。明治以来、成人年齢は２０歳で定着してきたが、改正公職選挙法で今年６月から引き下げられた選挙権年齢（１８歳以上）に合わせる。成立後、公布から施行まで少なくとも３年程度の周知期間を想定しており、早ければ平成３２年から導入されることになる。\" +\n\"法相の諮問機関の法制審議会は成人年齢の引き下げをめぐり、２１年に「１８歳に引き下げるのが適当」と答申しており、与野党を通じて異論は少ない。政府は、民法改正案を来年３月に閣議決定して来年の通常国会に提出する方針で、同国会で成立する見通しだ。\"+\n\"成人年齢が引き下げられた場合、飲酒、喫煙の解禁年齢や、少年法の適用年齢も「２０歳」（少年法は２０歳未満）から「１８歳」（同１８歳未満）に変更するかが大きな課題となる。ただ、これらの年齢引き下げには慎重論が根強く、今回は少年法改正案などの国会提出は見送る。\"+\n\"成人年齢見直しの議論は、憲法改正の手続きを定めた国民投票法が１９年５月に成立して始まった。国民投票法は投票年齢を原則１８歳以上としたが、成人年齢や選挙権年齢を１８歳に引き下げるなど関連制度が見直されるまでは２０歳以上としていた。\"+\n\"法制審が成人年齢の引き下げを「適当」と答申してから法改正に向けた具体的な動きはなかったが、昨年６月に選挙権年齢を「２０歳以上」から「１８歳以上」に引き下げる改正公職選挙法が成立。その後、自民党の特命委員会が成人年齢も速やかに１８歳に引き下げるよう求める提言をとりまとめるなど、成人年齢の見直し作業が加速していた。\";\n\nreturn msg;","outputs":1,"noerr":0,"x":382,"y":491.75,"wires":[["135f0d7b.ccc7fb"]]},{"id":"891202dc.b0881","type":"inject","z":"a8a4e460.ecf2c","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":141,"y":493,"wires":[["bba8d3ff.4d506"]]}]
```

flow in English:

```
[{"id":"feaafa00.b10af","type":"debug","z":"a8a4e460.ecf2c","name":"","active":true,"console":"false","complete":"insights","x":783.75,"y":569.75,"wires":[]},{"id":"aa101559.9cc62","type":"watson-personality-insights","z":"a8a4e460.ecf2c","name":"Sample English","lang":"en","x":593.75,"y":570.75,"wires":[["feaafa00.b10af"]]},{"id":"b898cab.65fdab8","type":"function","z":"a8a4e460.ecf2c","name":"Obama Speech","func":"msg.payload = \"THE PRESIDENT:  Well, with an introduction like that I should just stop now.  (Laughter.)  Carol, thank you so much.  And, Hank, and to the entire Goldberg clan -- there are all these gorgeous Goldberg kids running around somewhere.  And what a wonderful time to be here. \"+\n\"I see some really wonderful old friends who have been with us through the incredible journey, and I see some new friends.  I do remember that event at Eli Segal’s.  And Eli was such a great American and had provided such great service to the country, and obviously he’s missed.  But in some ways, his spirit lives on through all of us.  A lot of the work that we’ve pursued during the course of this administration reflects the values that he worked on so valiantly for so many years.\"+\n\"     I’m here because we’ve got an election.  And although Michelle is very strict about me actually taking a vacation when I get a vacation, she gave me a special dispensation for this evening because she understands, just as all of you understand, how important this is.\"+\n\"     It’s important because we have made extraordinary progress over the last eight years on a whole range of issues.  The economy, which was on the verge of collapse when I came into office, is, by almost every measure, better than it was eight years ago.  Unemployment has been slashed by more than half.  Incomes are up.  Wages have begun to go up.  We have seen 20 million people get health insurance that didn’t have it before.  We have doubled our production of clean energy.  We are as close to energy-independent as we’ve ever been.  We are seeing record graduation rates in high school -- and college enrollment rates. \"+\n\"     There’s a lot of good news out there.  And I could not be prouder of the part that our administration played in helping the American people rebound from what was an extraordinarily difficult time.  But what is also true is we’ve still got a lot of work to do.  Our job is not finished.  There are still too many people out there who, if they have a job, don’t make enough money to get beyond the worries of paying their bills at the end of the month.  There are still people who don’t have health insurance -- not because we haven’t tried, but because you have governors who have been resistant, or a Congress that has not wanted to work with us to close those final gaps in coverage that are so necessary.  \"+\n\"     Despite the extraordinary work that we’ve done in mobilizing 200 nations to, for the first time, tackle climate change in a comprehensive, aggressive way, we’ve still got a long way to go before we’re out of the woods on that one.  And that is a genuine existential threat that we all face and, more importantly, our children and our grandchildren face.\"+\n\"     We still have too much violence in our society.  There are still conflicts not just in the Middle East but around the world.  And given the rapidity of change, the pace of change that’s taken place, it is absolutely critical that we have a capable, visionary, hardworking, diligent, smart, tenacious leader in the Oval Office.  And that’s Hillary Clinton.  That’s who she is.  (Applause.)\"+\n\"     Now, a lot of you were at the convention in Philadelphia, and so you heard me and Joe Biden and Michelle and others make the case -- and you heard Hillary make the case herself.  I’m not going to belabor it.  I want to spend most of my time with questions. \"+\n\"The main thing I want to emphasize is that this is somebody who I know and I have worked alongside for many years.  And, look, I’m a Democrat, and so it’s fair to say that whoever the Democratic nominee was I would want to get behind them.  But I don’t display the kinds of enthusiasm and energy and commitment to Hillary’s candidacy just because of the fact that we belong to the same political party.\"+\n\"     When I say that she knows what she’s talking about, it’s because I have seen her do the work.  When I talk about her work ethic, it’s because I’ve watched her travel around the world and, at a breathless pace, manage a whole range of conflicts and open up opportunities that have resulted in American national security interests being served.  When I tell you that I’ve seen how she works not just with me, but with her staff and people below her in a way that is full of integrity and seriousness and good humor, it’s something that I’ve witnessed on a day-to-day basis. \"+\n\"And as I said at the convention, you don’t know ahead of time how you’re going to turn out as President.  You don’t -- you figure, “I seem to know what I’m talking about -- (laughter) -- I think I have a good sense of what’s involved.”  But until you sit at that desk and you’re making life-and-death decisions and you’re deploying young men and women to war, or you’re having to avert a crisis that can affect millions, or, in some cases, billions of lives, you don’t know how you’re going to respond.\"+\n\"But I will tell you that I have as good a guess when it comes to how Hillary will respond as I would of anybody’s, because I’ve seen her under really tough-pressure situations.  And that’s what’s needed right now.\"+\n\"What I also know is the passion that she feels for making sure that ordinary people in this country get a hand up, get a break; that somebody’s fighting for them.  Now, she’s not always the flashiest.  She’s not always the person who’s going to give you the big stem-winder.  But she is the person who’s going to do the work.  And whether it’s her advocacy for children, or her advocacy for health care, or her advocacy on behalf of equal pay or making sure that we’ve got child care for families that need it -- she hasn’t just talked the talk, she’s walked the walk for decades.  And my grandmother used to tell me, you want to judge how somebody is going to do, look at what they’ve done.  (Laughter.)  And she’s done the work. \"+\n\"So look, I know this is not an audience where I need to make a hard sell.  (Laughter.)  To some degree, I had you at hello -- (laughter) -- when it comes to voting for Hillary.  What I do want to emphasize is needing a sense of urgency and finishing the job of getting her elected.  And you notice I haven’t said much about her opponent.  (Laughter.)  Frankly, I’m tired of talking about her opponent.  I don’t have to make the case against her opponent because every time he talks he makes the case against his own candidacy. \"+\n\"But what I do know is that this has been an unpredictable election season, but -- not only because of anxieties and concerns that the American people have, but also because of the changing nature of the media and voting patterns.  There’s still a lot of uncertainty out there.  And if we are not running scared until the day after the election, we are going to be making a grave mistake.\"+\n\"And Democrats are interesting creatures.  We tend to veer from full-fledged freak-out, and “the world is ending and everything is terrible,” which -- I had conversations with some of you about three months ago, and it was -- the world was ending -- (laughter) -- to, “it’s going to be fine” and “who do you think she’s going to appoint for Commerce Secretary.”  (Laughter.)  And what I’d like us to do is veer somewhere in between those two extremes.  (Laughter.)\"+\n\"If we do our job, then Hillary will be elected President of the United States.  But if we do not do our jobs, then it’s still possible for her to lose.  And when I say “do our jobs,” what I mean is we are going to have to continue to be engaged.  We are going to continue to have to write checks.  We are going to continue to have to make phone calls, and rally people behind her candidacy.  We are still going to have to fight what has been a un-relenting negative campaign against her that has made a dent in the opinion of people even who are inclined to vote for her.\"+\n\"So we’ve got to be aggressive in our campaigning for 80 days.  And that’s not a lot.  But when you think about the stakes, there’s nothing more important.  This is a group that has been extraordinarily fortunate.  By definition, if you are here, you’ve had a blessed life, and your kids have been bequeathed and your grandchildren have been bequeathed extraordinary good fortune.  But as fortunate as you are, if we have a society of growing inequality, if we have a world where oceans are rising and droughts and famines are common occurrences, and millions of people are being displaced, and refugees are trying to find refuge someplace and crossing oceans and dying because they have no choice -- all of us will be poorer for it.  This will not be the kind of world that we want for our kids and our grandkids.\"+\n\"And to invest 80 days to make sure that we at least have a leader in the White House who understands that -- not because they’re going to be perfect, not because Hillary is going to solve every problem, just like I wasn’t perfect and I wasn’t able to solve every problem -- but at least somebody who understands what’s required and every single day is waking up and making best efforts to do it -- if we’re not willing to invest 80 days to make sure that happens, then shame on us. \"+\n\"So we’ve got to work.  And I don’t want to hear it about whether “I’m not sufficiently inspired,” or “we’ve got this in the bag,” or “I’ve got other things to do.”  You’ve got to work for 80 days.  And I’m glad to see some young people here.  I hope you volunteer and get involved in the campaign and do your part.  And if you do, then I continue to be, as I said in Philadelphia, extraordinarily optimistic about this greatest nation on Earth and the prospects for our future. \"+\n\"Thank you very much, everybody.  Thank you.  (Applause.)\";\n\nreturn msg;","outputs":1,"noerr":0,"x":341.75,"y":571.75,"wires":[["aa101559.9cc62"]]},{"id":"e92f01b4.ca2d9","type":"inject","z":"a8a4e460.ecf2c","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":128.75,"y":569.75,"wires":[["b898cab.65fdab8"]]}]
```

**Comment by chughts** [comment]
Thank you.

**Pull request merged**
